---
- name: Add Elasticsearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install Elasticsearch, Logstash, Kibana
  apt:
    name: ['elasticsearch', 'logstash', 'kibana']
    state: present

- name: Enable and start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - elasticsearch
    - logstash
    - kibana
